print "\nEnter the Amino acid sequence: ";
my $aa = <>;
chomp($aa);

$aa = uc($aa);
my $length = length($aa);

my $aromatic = ($aa =~ tr/FYW//);
my $aliphatic = ($aa =~ tr/GAVLIPM//);
my $polar = ($aa =~ tr/STNQYC//);
my $non_polar = ($aa =~ tr/GAVLIPMFW//);
my $acidic = ($aa =~ tr/DE//);
my $basic = ($aa =~ tr/KRH//);
my $sulfur_containing = ($aa =~ tr/CM//);
my $imino_acid = ($aa =~ tr/P//);
my $hydrophobic = ($aa =~ tr/GAVLIPMFW//);
my $hydrophilic = ($aa =~ tr/STNQYC//);
my $hydroxy = ($aa =~ tr/STM//);
my $essential = ($aa =~ tr/HILKMFTWV//);
my $non_essential = ($aa =~ tr/ANDEQGPSVC//);
my $glucogenic = ($aa =~ tr/ARNDCEQGHMPSV//);
my $ketogenic = ($aa =~ tr/LK//);
my $helix_breaker = ($aa =~ tr/P//);

my $aromatic_percent = ($aromatic / $length) * 100;
my $aliphatic_percent = ($aliphatic / $length) * 100;
my $polar_percent = ($polar / $length) * 100;
my $non_polar_percent = ($non_polar / $length) * 100;
my $acidic_percent = ($acidic / $length) * 100;
my $basic_percent = ($basic / $length) * 100;
my $sulfur_percent = ($sulfur_containing / $length) * 100;
my $imino_percent = ($imino_acid / $length) * 100;
my $hydrophobic_percent = ($hydrophobic / $length) * 100;
my $hydrophilic_percent = ($hydrophilic / $length) * 100;
my $hydroxy_percent = ($hydroxy / $length) * 100;
my $essential_percent = ($essential / $length) * 100;
my $non_essential_percent = ($non_essential / $length) * 100;
my $glucogenic_percent = ($glucogenic / $length) * 100;
my $ketogenic_percent = ($ketogenic / $length) * 100;
my $helix_breaker_percent = ($helix_breaker / $length) * 100;

print "\nAmino Acid composition: \n";
print "-----------------------------------\n";
print "Aromatic = $aromatic_percent%\n";
print "Aliphatic = $aliphatic_percent%\n";
print "Polar = $polar_percent%\n";
print "Non-polar = $non_polar_percent%\n";
print "Acidic = $acidic_percent%\n";
print "Basic = $basic_percent%\n";
print "Sulfur containing = $sulfur_percent%\n";
print "Imino acid = $imino_percent%\n";
print "Hydrophobic = $hydrophobic_percent%\n";
print "Hydrophilic = $hydrophilic_percent%\n";
print "Hydroxy = $hydroxy_percent%\n";
print "Essential = $essential_percent%\n";
print "Non-essential = $non_essential_percent%\n";
print "Glucogenic = $glucogenic_percent%\n";
print "Ketogenic = $ketogenic_percent%\n";
print "Helix-breaker = $helix_breaker_percent%\n";